[FEAT] enable setting gpu optimization variables
Nixtla/neuralforecast pull request #1186
Opened 2024-10-21 22:37 UTC by jasminerienecker

This is to allow adjusting the torch pin_memory and prefetch_factor variables to optimize gpu usage. 

Note: by adjusting these variables I am now able to increase GPU usage to 95% whereas with just the num_workers variable that is currently exposed to the interface, GPU usage hovers around 40-60%.

2024-10-21 22:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Nixtla/neuralforecast?pullRequest=1186) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Nixtla/neuralforecast?pullRequest=1186) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Nixtla/neuralforecast?pullRequest=1186) it.</sub>

2024-10-21 22:58 UTC, jmoralez commented
I'd prefer to introduce a single argument like `dataloader_kwargs` that gets passed to the dataloaders constructors and deprecate the `num_workers_loader` argument instead. That way we could also support `persistent_workers` for example.

2024-10-22 00:08 UTC, jasminerienecker commented
> I'd prefer to introduce a single argument like `dataloader_kwargs` that gets passed to the dataloaders constructors and deprecate the `num_workers_loader` argument instead. That way we could also support `persistent_workers` for example.

I've updated this - the review is now essentially a direct replacement of the num_workers variables with a dataloader_kwargs dictionary (with default None)

2024-10-23 23:13 UTC, jmoralez commented
Sorry, by deprecating I meant keeping the argument and then doing something like:

```python
if self.num_workers_loader != 0:  # value is not at its default
    warnings.warn(
        "The `num_workers_loader` argument is deprecated and will be removed in a future version. "
        "Please provide num_workers through `dataloader_kwargs`, e.g. "
        f"`dataloader_kwargs={'num_workers': {self.num_workers_loader}`",
        category=FutureWarning,
    )
dataloader_kwargs['num_workers'] = self.num_workers_loader
```

2024-10-24 10:44 UTC, jasminerienecker commented
> Sorry, by deprecating I meant keeping the argument and then doing something like:
> 
> 
> 
> ```python
> 
> if self.num_workers_loader != 0:  # value is not at its default
> 
>     warnings.warn(
> 
>         "The `num_workers_loader` argument is deprecated and will be removed in a future version. "
> 
>         "Please provide num_workers through `dataloader_kwargs`, e.g. "
> 
>         f"`dataloader_kwargs={'num_workers': {self.num_workers_loader}`",
> 
>         category=FutureWarning,
> 
>     )
> 
> dataloader_kwargs['num_workers'] = self.num_workers_loader
> 
> ```

@jmoralez ah yes I see - I've put that back in now and added the deprecation warnings to the base models class

2024-10-30 19:48 UTC, jmoralez commented
Thanks! Sorry, I messed up the suggestion, we should do the `dataloader_kwargs['num_workers'] = self.num_workers_loader` inside the `if` block, otherwise we'll override them every time, instead of just when the user wants to set it.

2024-10-31 04:11 UTC, jasminerienecker commented
@jmoralez makes sense - that should be updated in both cases now!

2024-10-31 17:17 UTC, jmoralez commented
Thanks! I'm very sorry, I just realized from your changes to `BaseRecurrent` that we have a similar argument for predict called `data_module_kwargs`, although I don't think you can provide useful arguments to the data module through it, just `batch_size`, `drop_last` and `shuffle_train` which aren't used during predict.

@cchallu what's the purpose of the `data_module_kwargs` argument?

2024-10-31 17:19 UTC, jmoralez commented
@jasminerienecker in the meantime, can you please revert the changes to the predict method of `BaseRecurrent`? We can limit this PR to adding arguments to the training step.

2024-11-03 22:54 UTC, jasminerienecker commented
@jmoralez all good - that's now been updated

2024-11-04 18:41 UTC, jmoralez approved these changes
Thanks!

2024-11-05 15:38 UTC, jmoralez requested changes

2024-11-05 15:38 UTC, jmoralez commented on neuralforecast/common/_base_recurrent.py
> -            num_workers=self.num_workers_loader,
We should keep this for now

2024-11-08 16:21 UTC, jmoralez approved these changes

2024-11-08 17:20 UTC, merged