Static variables
Nixtla/neuralforecast pull request #305
Opened 2022-10-27 17:45 UTC by cchallu

* Added static exogenous variables to all models.
* Refactor TFT only to include continuous variables.
* Added static_df input to the core.NeuralForecast methods.
* Include usage examples in all models using core.NeuralForecast class.

2022-10-27 20:10 UTC, kdgutier requested changes
Really cool!

- Lets add the new `static_df` input to the core methods' docstrings.
- Lets clean TFT's commented outdated code.
- Lets make the calls to the TFT methods, to have the name of the inputs to improve robustness.
- Lets institutionalize the static alignment unit test with nbdev_tests

2022-10-27 20:10 UTC, kdgutier commented on neuralforecast/models/tft.py
> -        self.s_cont_inp_size = s_cont_inp_size
Lets take the commented code out, instead of keeping it here.

2022-10-27 20:10 UTC, kdgutier commented on neuralforecast/models/tft.py
> +        s_inp = self._apply_embedding(stat_exog,
Let's protect this calls by naming the inputs.
In future revisions of the code we might change the order of the inputs and we can make this robust.

2022-10-28 15:24 UTC, cchallu commented on neuralforecast/common/_base_windows.py
> +                                 temporal_cols=temporal_cols,
We need to implement tests for all temporal, static covariates. We will do a full sprint on these tests in the future.

2022-10-31 15:17 UTC, kdgutier approved these changes

2022-10-31 15:17 UTC, merged